name: Build NPM

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-npm.yml'
      - 'src/**'
      - '*.ts'
      - '*.js'
      - '*.json'
      - '*.yaml'
      - 'pnpm-lock.yaml'

concurrency:
  group: build-npm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-npm:
    uses: chenasraf/workflows/.github/workflows/nextcloud-build-npm.yml@nextcloud-latest
    secrets: inherit
