name: Lint php-cs

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '.php-cs-fixer.dist.php'
      - '.github/workflows/lint-php-cs.yml'

concurrency:
  group: lint-php-cs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-php-cs:
    uses: chenasraf/workflows/.github/workflows/nextcloud-lint-php-cs.yml@nextcloud-latest
    secrets: inherit
