name: Lint OpenAPI

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'lib/**/*.php'
      - 'openapi.json'
      - '.github/workflows/lint-openapi.yml'

concurrency:
  group: openapi-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-openapi:
    uses: chenasraf/workflows/.github/workflows/nextcloud-lint-openapi.yml@nextcloud-latest
    secrets: inherit
