name: Lint appinfo.xml

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'appinfo/info.xml'
      - '.github/workflows/lint-appinfo-xml.yml'

concurrency:
  group: lint-info-xml-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-appinfo-xml:
    uses: chenasraf/workflows/.github/workflows/nextcloud-lint-appinfo-xml.yml@nextcloud-latest
    secrets: inherit
